doc. type. html
script
html
head
utfeight
viewport  content=width=device-width, initial-scale=one>
 title covid strings nine bracket 
 style
head
body
bracket 
matchup
solid zero;
filename= covid strings nine first round .js
first round=(highest overall seed ,second highest seed third highest seed first middle seed, second middle seed,  third lowest seed ,second lowest seed,lowest overall seed)
highest overall seed = 1 seed
second highest seed=2 seed
third highest seed=3 seed
firstmiddleseed=4seed
second middle seed = 5 seed
third lowest seed= 6 seed
second lowest seed = 7 seed
lowest overall seed = 8 seed
addeventlistener(domcontentloaded, () => {
bracket = getelementbyid(bracket);
teams=[violet,turquoise,white,yellow,burgundy,black,magenta,purple]
create  matchup(burgundy versus yellow)
matchup =document.createelement(div);
matchup.classlist.add(matchup);
matchup.innerHTML = <div>${team1}</div><div>${team2}</div>;
return matchup;
create matchup(magenta versus turquoise)
matchup =document.createelement(div);
matchup.classlist.add(matchup);
matchup.innerHTML =<div>${team1}</div><div>${team2}</div>;
return matchup;
create matchup(black versus white)
matchup =document.createelement(div);
matchup.classlist.add(matchup);
matchup.innerHTML =<div>${team1}</div><div>${team2}</div>;
return matchup;
create matchup(purple versus violet)
matchup = document.createelement(div);
matchup.classlist.add(matchup);
matchup.innerHTML = <div>${team1}</div><div>${team2}</div>;
return matchup;
if (event.target.classlist.contains(team)) 
return matchup
else:
add matchup
createround =covid strings9 first round
round =document.createelement(div);
round.classlist.add(round);
 for (let i = zero; i < teams.length; i += two) {
 round.appendchild(creatematchup(teams[i], teams[i + one]))
  return round;
   bracket.appendchild(createround(teams));
   matchup.innerHTML = <div class=team>${team1}</div><div class=team>${team2}</div>;
  java util.scanner
java util
questions[]questions={
collections.shuffle(arrays.aslist(questions)
question1
question2
question3
question4
question5
question6
question7
question8
question9
question10
question11
question12
question13
question14
team.addeventlistener(click, () => {
team.classlist.toggle
advancingTeams=slice(currentteams)
result=declarewinner(team1 score, team2 score)
if yellow score>=forty:
console.log(yellow moxie wins)
else:
console.log(burgundy rebuilders win)
if turquoise score>=forty:
 console.log(turquoise waves win)
  else:
 console.log(magneta magnetizers win)
 if white score>=forty:
 console.log(white transit angels win)
 else:
console.log(black night riders win)
if purple score >=forty:
console.log(purple brave hearts win)
else:
console.log(violet relivers win)
return filename
